# Generated by Django 3.2.9 on 2022-01-03 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prev_owners',
            field=models.ManyToManyField(related_name='was_owned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
