# Generated by Django 3.2.9 on 2022-01-06 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_prev_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='prev_owners',
        ),
        migrations.AddField(
            model_name='item',
            name='prev_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='was_owned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
